name: Migrations

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Migrations
    steps:
      - uses: actions/checkout@v4

      - name: Generate migrations
        run: npm install && npm run db:generate

      - name: Migrations
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: d1 migrations apply d1-hello-hono

